#!/usr/bin/env python3
# by William Hofferbert
#
# This is a TCP server, which listens for information that is being
# broadcast at it via a combination of Teensy LC (analog monitor)
# and ESP8266 (serial data intake to Wifi)
#
# You need to set up the appropriate objects based on their key name
# that will be within the data coming from the teensy/ESP
#
# This project uses A1, A2, A3, A4 for 4 analog keys (potentiometers)
# and it uses D1, D2, for two digital keys (switches)
#

########################################################################
#
#
# midi variable definitions/imports
#
#
########################################################################

import mido
import os
import re
import time
from midiThing import midiThing

# midi device naming and setup
midiName = "Teensy-ESP-WiFi-MIDI"

# key name as it appears in tcp data = midiThing(midiChannel, midiCcNumber, initial value)
A1 = midiThing(0, 7, 64)
A2 = midiThing(0, 13, 64)
A3 = midiThing(0, 9, 64)
A4 = midiThing(0, 10, 64)

D1 = midiThing(0, 11, 0)
D2 = midiThing(0, 12, 0)

# wait some seconds for other software after reboot
init_sleep_secs = 2

########################################################################
#
#
# TCP server definitions/imports
#
#
########################################################################

import socket
import sys

# number of characters (bytes) to wait for
# should be a small power of 2 (ie 4096) re: https://docs.python.org/3/library/socket.html
data_intake_limit = 128
#data_intake_limit = 1024

# server address/port
server_address = ("172.24.1.1", 1234)

########################################################################
#
#
# midi definitions/functions
#
#
########################################################################

#
# sends a midi control change message to midi_output_device, which
# was created earlier
#

def send_cc(channel, ccnum, val):
    msg = mido.Message('control_change', channel=channel, control=ccnum, value=val)
    output = mido.open_output(midi_output_device)
    output.send(msg)

#
# iterate through midi things and see if we need to send CC messages
#

def update_midi(data_keyvals):
    for key, val in data_keyvals.items():
        # update the object we are dealing with
        try:
            keyObj = globals()[key]
            keyObj.update(val)
            # if any objects have changed values
            if globals()[key].has_changed():
                #   send midi data
                channel = keyObj.channel
                ccNum = keyObj.ccNum
                midiVal = int(float(val))
                if (midiVal < 0 or midiVal > 127):
                    print("BAD VAL: key:", str(key), " changed to:", str(val))
                    next
                else:
                    print("key:", str(key), " has changed to:", str(val))
                    send_cc(channel, ccNum, midiVal)
        except KeyError:
            print("Got bad key:", key)
            next

#
# check_for_running_midi returns true if amidithru with the
# desired name is running already
#
# If so, assume to use that, since it's probably leftover
# from an earlier test/change.
#

def check_for_running_midi():
    # TODO make this better
    # so shitty, not pythonic at all
    # if only I weren't a linux sysadmin
    checkGrep = 'ps -ef | grep -Po "amidithru\s*' + midiName + '" | grep -v grep >/dev/null'
    check = os.system(checkGrep)
    #print("check val is %s" % check)
    # 0 = running
    # 256/anything else = nope
    return check

#
# this sets up the midi device via system and amidithru
#

def setup_midi_backend():
    # set up backend
    mido.set_backend('mido.backends.rtmidi')

    # system command to set up the midi thru port
    if check_for_running_midi() != 0:
        runCmd = "amidithru '" + midiName + "' &"
        os.system(runCmd)
        # wait a sec for amidithru to do it's thing
        time.sleep(1)
    
    # regex to match on rtmidi port name convention
    # TODO is it necessary to write:  "\s+(\d+)?:\d+)"  instead?
    nameRegex = "(" + midiName + ":" + midiName + "\s+\d+:\d+)"
    matcher = re.compile(nameRegex)
    newList = list(filter(matcher.match, mido.get_output_names()))
    # all to get the name of the thing we just made
    global midi_output_device
    midi_output_device = newList[0]


########################################################################
#
#
# TCP defs/funcs
#
#
########################################################################

#
# This class sets up a rolling string that we do regex matches on to find 
# new data that we can work with.
#

class dataIntake(object):
    def __init__(self):
        self.data = ""

    def update(self, value):
        self.data += value
        #self.current = value

    def get_workable_data(self):
        # return array of bits that match what we can
        # TODO this might be more complicated than it needs to be
        # perhaps just split on ! and investigate those parts
        regex = r'(([AD]\d+:\d+;)+([AD]\d+:\d+))!'
        # match on all possible bits
        matches = re.findall(regex, self.data)
        myRet = []
        if matches:
            i = 0
            for m in matches:
                # first matching group (long str except !) is the key here
                #print("matched job %s: %s", i, m[0])
                i += 1
                myRet.append(m[0])
            # zero out data for new incoming stuff
            #print("zeroing out self data")
            self.data = ""
        #else:
        #    #print("no match for workable data")
        return myRet

#
# this picks apart the data from the teensy/esp and passes the sanitized
# information over to update_midi()
#

def analog_to_midival(data):
    arr = data.split(";")
    midi_data = {}
    for item in arr:
        pattern = r'([AD]\d+):(\d+)'
        results = re.search(pattern, item)
        objKey = ""
        objVal = ""
        try:
            objKey = results.group(1)
            objVal = results.group(2)
        except:
            print('bad split on regex! data: %s' % data, file=sys.stderr, flush=True)
            return
        if (re.match('A\d+', objKey)):
            midival = (int(objVal) * 127) / 1024
            truncate = '%.02f' % midival
            midi_data[objKey] = truncate
        if (re.match('D\d+', objKey)):
            midival = (int(objVal) * 127)
            midi_data[objKey] = midival
    # dict gets passed to another def for handling...
    update_midi(midi_data)


#
# This bit is in charge of getting the ball rolling and waiting for the
# teensy/esp to start going
#

def start_tcp_to_midi_server():
    # wait some secs
    time.sleep(init_sleep_secs)

    # maybe start midi output device
    setup_midi_backend()

    # tcp server object, create it
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    # disable nagle
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
    sock.bind(server_address)

    # Listen for incoming connections
    sys.stderr.write('starting up on %s port %s\n' % server_address)
    sock.listen(1)

    myDataIntake = dataIntake()

    while True:
        # Wait for a connection
        connection, client_address = sock.accept()
        try:
            while True:
                # receive chunk of data
                data = connection.recv(data_intake_limit).decode('utf-8')
                # update object with data
                myDataIntake.update(data)
                #print("Current working data is: %s" % myDataIntake.data)
                # for every workable piece of data
                for job in myDataIntake.get_workable_data():
                    # update things
                    analog_to_midival(job)
        finally:
            # Clean up the connection
            connection.close()

#
# hey, you can import this if you want (but don't forget about midiThing)
#

if __name__ == "__main__":
    start_tcp_to_midi_server()
